// <auto-generated />
using BolaoDaCopa2026.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BolaoDaCopa2026.Migrations
{
    [DbContext(typeof(BolaoContext))]
    [Migration("20260108195818_CreateSelecoes")]
    partial class CreateSelecoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4");

            modelBuilder.Entity("BolaoDaCopa2026.Models.Aposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApostadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsSelecaoA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsSelecaoB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelecaoAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelecaoBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApostadorId");

                    b.HasIndex("SelecaoAId");

                    b.HasIndex("SelecaoBId");

                    b.ToTable("Apostas");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Apostador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PalpitesExatos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Apostadores");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Selecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Derrotas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Empates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsContra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsPro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Jogos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vitorias")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Selecoes");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Aposta", b =>
                {
                    b.HasOne("BolaoDaCopa2026.Models.Apostador", "Apostador")
                        .WithMany("Apostas")
                        .HasForeignKey("ApostadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolaoDaCopa2026.Models.Selecao", "SelecaoA")
                        .WithMany()
                        .HasForeignKey("SelecaoAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolaoDaCopa2026.Models.Selecao", "SelecaoB")
                        .WithMany()
                        .HasForeignKey("SelecaoBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apostador");

                    b.Navigation("SelecaoA");

                    b.Navigation("SelecaoB");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Apostador", b =>
                {
                    b.HasOne("BolaoDaCopa2026.Models.Usuario", "Usuario")
                        .WithOne("Apostador")
                        .HasForeignKey("BolaoDaCopa2026.Models.Apostador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Apostador", b =>
                {
                    b.Navigation("Apostas");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Usuario", b =>
                {
                    b.Navigation("Apostador")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
