// <auto-generated />
using System;
using BolaoDaCopa2026.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BolaoDaCopa2026.Migrations
{
    [DbContext(typeof(BolaoContext))]
    [Migration("20260201162752_PontosNaApostaERecalculo")]
    partial class PontosNaApostaERecalculo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4");

            modelBuilder.Entity("BolaoDaCopa2026.Models.Aposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApostadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsSelecaoA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsSelecaoB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pontos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelecaoAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelecaoBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApostadorId");

                    b.HasIndex("JogoId");

                    b.HasIndex("SelecaoAId");

                    b.HasIndex("SelecaoBId");

                    b.ToTable("Apostas");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Apostador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPago")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PalpitesExatos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Apostadores");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApostasProcessadas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClassificacaoProcessada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaAberto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GolsSelecaoA")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GolsSelecaoB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelecaoAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelecaoBId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelecaoAId");

                    b.HasIndex("SelecaoBId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Selecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BandeiraUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Derrotas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Empates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsContra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsPro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<int>("Jogos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pontos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vitorias")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Selecoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BandeiraUrl = "https://flagcdn.com/w40/mx.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "A",
                            Jogos = 0,
                            Nome = "México",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 2,
                            BandeiraUrl = "https://flagcdn.com/w40/za.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "A",
                            Jogos = 0,
                            Nome = "África do Sul",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 3,
                            BandeiraUrl = "https://flagcdn.com/w40/kr.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "A",
                            Jogos = 0,
                            Nome = "Coreia do Sul",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 4,
                            BandeiraUrl = "https://flagcdn.com/w40/eu.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "A",
                            Jogos = 0,
                            Nome = "Repescagem Europa D",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 5,
                            BandeiraUrl = "https://flagcdn.com/w40/ca.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "B",
                            Jogos = 0,
                            Nome = "Canadá",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 6,
                            BandeiraUrl = "https://flagcdn.com/w40/eu.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "B",
                            Jogos = 0,
                            Nome = "Repescagem Europa A",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 7,
                            BandeiraUrl = "https://flagcdn.com/w40/qa.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "B",
                            Jogos = 0,
                            Nome = "Catar",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 8,
                            BandeiraUrl = "https://flagcdn.com/w40/ch.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "B",
                            Jogos = 0,
                            Nome = "Suíça",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 9,
                            BandeiraUrl = "https://flagcdn.com/w40/br.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "C",
                            Jogos = 0,
                            Nome = "Brasil",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 10,
                            BandeiraUrl = "https://flagcdn.com/w40/ma.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "C",
                            Jogos = 0,
                            Nome = "Marrocos",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 11,
                            BandeiraUrl = "https://flagcdn.com/w40/ht.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "C",
                            Jogos = 0,
                            Nome = "Haiti",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 12,
                            BandeiraUrl = "https://flagcdn.com/w40/gb-sct.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "C",
                            Jogos = 0,
                            Nome = "Escócia",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 13,
                            BandeiraUrl = "https://flagcdn.com/w40/us.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "D",
                            Jogos = 0,
                            Nome = "Estados Unidos",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 14,
                            BandeiraUrl = "https://flagcdn.com/w40/py.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "D",
                            Jogos = 0,
                            Nome = "Paraguai",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 15,
                            BandeiraUrl = "https://flagcdn.com/w40/au.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "D",
                            Jogos = 0,
                            Nome = "Austrália",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 16,
                            BandeiraUrl = "https://flagcdn.com/w40/eu.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "D",
                            Jogos = 0,
                            Nome = "Repescagem Europa C",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 17,
                            BandeiraUrl = "https://flagcdn.com/w40/de.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "E",
                            Jogos = 0,
                            Nome = "Alemanha",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 18,
                            BandeiraUrl = "https://flagcdn.com/w40/cw.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "E",
                            Jogos = 0,
                            Nome = "Curaçao",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 19,
                            BandeiraUrl = "https://flagcdn.com/w40/ci.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "E",
                            Jogos = 0,
                            Nome = "Costa do Marfim",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 20,
                            BandeiraUrl = "https://flagcdn.com/w40/ec.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "E",
                            Jogos = 0,
                            Nome = "Equador",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 21,
                            BandeiraUrl = "https://flagcdn.com/w40/nl.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "F",
                            Jogos = 0,
                            Nome = "Holanda",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 22,
                            BandeiraUrl = "https://flagcdn.com/w40/jp.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "F",
                            Jogos = 0,
                            Nome = "Japão",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 23,
                            BandeiraUrl = "https://flagcdn.com/w40/eu.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "F",
                            Jogos = 0,
                            Nome = "Repescagem Europa B",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 24,
                            BandeiraUrl = "https://flagcdn.com/w40/tn.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "F",
                            Jogos = 0,
                            Nome = "Tunísia",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 25,
                            BandeiraUrl = "https://flagcdn.com/w40/be.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "G",
                            Jogos = 0,
                            Nome = "Bélgica",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 26,
                            BandeiraUrl = "https://flagcdn.com/w40/eg.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "G",
                            Jogos = 0,
                            Nome = "Egito",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 27,
                            BandeiraUrl = "https://flagcdn.com/w40/ir.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "G",
                            Jogos = 0,
                            Nome = "Irã",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 28,
                            BandeiraUrl = "https://flagcdn.com/w40/nz.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "G",
                            Jogos = 0,
                            Nome = "Nova Zelândia",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 29,
                            BandeiraUrl = "https://flagcdn.com/w40/es.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "H",
                            Jogos = 0,
                            Nome = "Espanha",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 30,
                            BandeiraUrl = "https://flagcdn.com/w40/cv.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "H",
                            Jogos = 0,
                            Nome = "Cabo Verde",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 31,
                            BandeiraUrl = "https://flagcdn.com/w40/sa.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "H",
                            Jogos = 0,
                            Nome = "Arábia Saudita",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 32,
                            BandeiraUrl = "https://flagcdn.com/w40/uy.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "H",
                            Jogos = 0,
                            Nome = "Uruguai",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 33,
                            BandeiraUrl = "https://flagcdn.com/w40/fr.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "I",
                            Jogos = 0,
                            Nome = "França",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 34,
                            BandeiraUrl = "https://flagcdn.com/w40/sn.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "I",
                            Jogos = 0,
                            Nome = "Senegal",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 35,
                            BandeiraUrl = "https://flagcdn.com/w40/un.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "I",
                            Jogos = 0,
                            Nome = "Repescagem Intercontinental 2",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 36,
                            BandeiraUrl = "https://flagcdn.com/w40/no.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "I",
                            Jogos = 0,
                            Nome = "Noruega",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 37,
                            BandeiraUrl = "https://flagcdn.com/w40/ar.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "J",
                            Jogos = 0,
                            Nome = "Argentina",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 38,
                            BandeiraUrl = "https://flagcdn.com/w40/dz.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "J",
                            Jogos = 0,
                            Nome = "Argélia",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 39,
                            BandeiraUrl = "https://flagcdn.com/w40/at.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "J",
                            Jogos = 0,
                            Nome = "Áustria",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 40,
                            BandeiraUrl = "https://flagcdn.com/w40/jo.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "J",
                            Jogos = 0,
                            Nome = "Jordânia",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 41,
                            BandeiraUrl = "https://flagcdn.com/w40/pt.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "K",
                            Jogos = 0,
                            Nome = "Portugal",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 42,
                            BandeiraUrl = "https://flagcdn.com/w40/un.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "K",
                            Jogos = 0,
                            Nome = "Repescagem Intercontinental 1",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 43,
                            BandeiraUrl = "https://flagcdn.com/w40/uz.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "K",
                            Jogos = 0,
                            Nome = "Uzbequistão",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 44,
                            BandeiraUrl = "https://flagcdn.com/w40/co.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "K",
                            Jogos = 0,
                            Nome = "Colômbia",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 45,
                            BandeiraUrl = "https://flagcdn.com/w40/gb-eng.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "L",
                            Jogos = 0,
                            Nome = "Inglaterra",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 46,
                            BandeiraUrl = "https://flagcdn.com/w40/hr.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "L",
                            Jogos = 0,
                            Nome = "Croácia",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 47,
                            BandeiraUrl = "https://flagcdn.com/w40/gh.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "L",
                            Jogos = 0,
                            Nome = "Gana",
                            Pontos = 0,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 48,
                            BandeiraUrl = "https://flagcdn.com/w40/pa.png",
                            Derrotas = 0,
                            Empates = 0,
                            GolsContra = 0,
                            GolsPro = 0,
                            Grupo = "L",
                            Jogos = 0,
                            Nome = "Panamá",
                            Pontos = 0,
                            Vitorias = 0
                        });
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Aposta", b =>
                {
                    b.HasOne("BolaoDaCopa2026.Models.Apostador", "Apostador")
                        .WithMany("Apostas")
                        .HasForeignKey("ApostadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolaoDaCopa2026.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolaoDaCopa2026.Models.Selecao", "SelecaoA")
                        .WithMany()
                        .HasForeignKey("SelecaoAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolaoDaCopa2026.Models.Selecao", "SelecaoB")
                        .WithMany()
                        .HasForeignKey("SelecaoBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apostador");

                    b.Navigation("Jogo");

                    b.Navigation("SelecaoA");

                    b.Navigation("SelecaoB");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Apostador", b =>
                {
                    b.HasOne("BolaoDaCopa2026.Models.Usuario", "Usuario")
                        .WithOne("Apostador")
                        .HasForeignKey("BolaoDaCopa2026.Models.Apostador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Jogo", b =>
                {
                    b.HasOne("BolaoDaCopa2026.Models.Selecao", "SelecaoA")
                        .WithMany()
                        .HasForeignKey("SelecaoAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolaoDaCopa2026.Models.Selecao", "SelecaoB")
                        .WithMany()
                        .HasForeignKey("SelecaoBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SelecaoA");

                    b.Navigation("SelecaoB");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Apostador", b =>
                {
                    b.Navigation("Apostas");
                });

            modelBuilder.Entity("BolaoDaCopa2026.Models.Usuario", b =>
                {
                    b.Navigation("Apostador")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
